--EXPLORATORY DATA ANALYSIS

-- Explore all objects in the database
select * from INFORMATION_SCHEMA.TABLES

select * from gold.dim_customers 
select * from gold.dim_products
select * from gold.fact_sales

-- Explore all columns in the database
select * from INFORMATION_SCHEMA.COLUMNS


--EXPLORE ALL COUNTRIES OUR CUSTOMERS COME FROM.

select distinct country  from gold.dim_customers

-- EXPLORE ALL MAJOR CATEGORIES " THE MAJOR DIVISIONS"

select distinct category, subcategory, product_name from gold.dim_products
order by 1,2,3

-- FIRST AND LAST ORDER DATE
select 
min(order_date) as first_order_date,
max(order_date) as last_order_date,
datediff(year, min(order_date), max(order_date) ) as order_range_years
from gold.fact_sales

-- FIND YOUNGEST AND OLDEST CUSTOMERS
select 
min(birthdate) as bday_youngest_cust,
datediff(year, min(birthdate) , GETDATE()) as Age_Oldest,
max(birthdate) as bday_oldest_cust,
datediff(year, max(birthdate) , GETDATE()) as Age_Youngest,
datediff(year, min(birthdate) , max(birthdate)) as Age_Gap
from gold.dim_customers

--MEASURES EXPLORATION
--TOTAL SALES
select sum(sales_amount) as Total_Sales from gold.fact_sales

-- HOW MANY ITEMS ARE SOLD
select sum(quantity) as Total_Quantity from gold.fact_sales

-- AVERAGE SELLING PRICE
select AVG(price) as Avg_Selling_Price from gold.fact_sales

-- TOTAL NUMBER OF ORDERS
select count(order_number) as Total_Orders from gold.fact_sales

select count(distinct(order_number)) as Total_distinct_Orders from gold.fact_sales

-- TOTAL NUMBER OF PRODUCTS
select count(distinct(product_id)) as Total_Products from gold.dim_products

--TOTAL NUMBER OF CUSTOMERS
select count(distinct(customer_id)) as Total_Customers from gold.dim_customers

-- TOTAL NUMBER OF CUSTOMERS THAT HAS PLACED AN ORDER
select count(distinct(customer_key)) as Cust_with_Orders from gold.fact_sales



-- Generate a Report that shows all key metrics of the business
SELECT 'Total Sales' AS Measure_Name, SUM(sales_amount) AS Measure_Value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity', SUM(quantity) FROM gold.fact_sales
UNION ALL
SELECT 'Average Price', AVG(price) FROM gold.fact_sales
UNION ALL
SELECT 'Total Orders', COUNT(DISTINCT order_number) FROM gold.fact_sales
UNION ALL
SELECT 'Total Products', COUNT(DISTINCT product_name) FROM gold.dim_products
UNION ALL
SELECT 'Total Customers', COUNT(customer_key) FROM gold.dim_customers;

--MAGNITUDE ANALYSIS

-- TOTAL CUSTOMERS BY COUNTRIES
SELECT 
country,
COUNT(customer_id) as Total_Customers
from gold.dim_customers
group by country
order by Total_Customers desc

-- TOTAL CUSTOMERS BY GENDER
SELECT 
gender,
COUNT(customer_id) as Total_Customers
from gold.dim_customers
group by gender
order by Total_Customers desc

--TOTAL PRODUCTS BY CATEGORY
SELECT 
category,
COUNT(product_id) as Total_Products
from gold.dim_products
group by category
order by Total_Products desc

-- AVERAGE COST IN EACH CATEGORY
SELECT 
category,
Avg(cost) as Avg_Cost
from gold.dim_products
group by category
order by Avg_Cost desc


--TOTAL REVENUE GENERATED FOR EACH CATEGORY
SELECT 
p.category,
sum(s.sales_amount) as Revenue
from gold.fact_sales s
left join gold.dim_products p
on s.product_key = p.product_key
group by category
order by Revenue desc
;
--TOTAL REVENUE GENERATED BY EACH CUSTOMER
select 
c.customer_key,
c.first_name,
c.last_name,
sum(s.sales_amount) as Revenue
from gold.fact_sales s
left join gold.dim_customers c
on s.customer_key = c.customer_key
group by c.customer_key, c.first_name, c.last_name
order by Revenue Desc

-- DISTRIBUTION OF SOLD ITEMS ACROSS COUNTRIES
select 
c.country,
sum(s.quantity) as Total_Sold_Item
from gold.fact_sales s
left join gold.dim_customers c
on s.customer_key = c.customer_key
group by c.country
order by Total_Sold_Item Desc


-- RANKING ANALYSIS

-- TOP 5 REVENUE GENERATING PRODUCTS
select top 5 p.product_key,
p.product_name,
sum(s.sales_amount) as Revenue
from gold.fact_sales s
left join gold.dim_products p
on s.product_key = p.product_key
group by p.product_key, p.product_name
order by Revenue Desc

-- using window functions
select * from (
                select p.product_key,
                p.product_name,
                sum(s.sales_amount) as Revenue,
                row_number() over (order by  sum(s.sales_amount) desc ) as Ranking 
                from gold.fact_sales s
                left join gold.dim_products p
                on s.product_key = p.product_key
                group by p.product_key, p.product_name )t
where Ranking < 6
 
-- TOP 5 WORST PERFORMING PRODUCTS
select top 5 p.product_key,
p.product_name,
sum(s.sales_amount) as Revenue
from gold.fact_sales s
left join gold.dim_products p
on s.product_key = p.product_key
group by p.product_key, p.product_name
order by Revenue Asc

-- TOP 5 REVENUE GENERATING SUBCATEGORIES
select top 5 p.subcategory ,
sum(s.sales_amount) as Revenue
from gold.fact_sales s
left join gold.dim_products p
on s.product_key = p.product_key
group by p.subcategory
order by Revenue Desc

-- TOP 5 WORST PERFORMING SUBCATEGORIES
select top 5 p.subcategory ,
sum(s.sales_amount) as Revenue
from gold.fact_sales s
left join gold.dim_products p
on s.product_key = p.product_key
group by p.subcategory
order by Revenue Asc


-- TOP 10 CUSTOMERS WHO GENERATED HIGHEST REVENUE
select top 10
c.customer_key,
c.first_name,
c.last_name,
sum(s.sales_amount) as Revenue
from gold.fact_sales s
left join gold.dim_customers c
on s.customer_key = c.customer_key
group by c.customer_key, c.first_name, c.last_name
order by Revenue Desc

-- 3 CUSTOMERS WITH FEWEST ORDERS PLACED
select top 3
c.customer_key,
c.first_name,
c.last_name,
count(distinct(s.order_number)) as Total_Orders
from gold.fact_sales s
left join gold.dim_customers c
on s.customer_key = c.customer_key
group by c.customer_key, c.first_name, c.last_name
order by Total_Orders Asc

-- ADVANCED ANALYTICS

-- SALES PERFORMANCE OVER TIME

-- YEAR-WISE
select 
year(order_date) as Years ,
count(distinct(customer_key)) as Total_Customers,
sum(sales_amount) as Total_Revenue,
sum(quantity) as Total_Items_sold
from gold.fact_sales
where order_date is not null
group by year(order_date)
order by year(order_date)

-- MONTH-WISE
select 
month(order_date) SL_NO,
format(order_date, 'MMMM') as months ,
count(distinct(customer_key)) as Total_Customers,
sum(sales_amount) as Total_Revenue,
sum(quantity) as Total_Items_sold
from gold.fact_sales
where order_date is not null
group by format(order_date, 'MMMM'), month(order_date)
order by month(order_date)


-- CUMILATIVE ANALYSIS

-- TOTAL SALES PER MONTH, RUNNING TOTAL OF SALES OVER TIME AND MOVING AVERAGE OF PRICE
select *,
sum(Total_Sales) over (partition by  DATETRUNC(year, Months) order by Months) as Running_Total_Sales,
Avg(Avg_Price) over (partition by  DATETRUNC(year, Months) order by Months) as Moving_Avg
from (
    select 
    DATETRUNC(month, order_date) as Months,
    sum(sales_amount) as Total_Sales,
    Avg(price) as Avg_Price
    from gold.fact_sales
    where order_date is not null
    group by DATETRUNC(month, order_date))t

-- TOTAL SALES PER YEAR, RUNNING TOTAL OF SALES OVER TIME AND MOVING AVERAGE OF PRICE
select *,
sum(Total_Sales) over (order by Years) as Running_Total_Sales,
Avg(Avg_Price) over ( order by Years) as Moving_Avg
from (
    select 
    DATETRUNC(year, order_date) as Years,
    sum(sales_amount) as Total_Sales,
    Avg(price) as Avg_Price
    from gold.fact_sales
    where order_date is not null
    group by DATETRUNC(year, order_date))t


-- PERFORMANCE ANALYSIS

/* ANALYSING THE YEARLY PERFORMANCE OF PRODUCTS BY COMPARING THEIR SALES TO BOTH 
   THE AVERAGE SALES PERFORMANCE OF THE PRODUCT AND THE PREVIOUS YEAR'S SALES*/
with yearly_product_sales as 
                             (
                             select
                             year(s.order_date) as Years,
                             p.product_name,
                             sum(s.sales_amount) as Current_Sales
                             from gold.fact_sales s
                             left join gold.dim_products p
                             on s.product_key = p.product_key
                             where year(s.order_date) is not null
                             group by year(s.order_date),  p.product_name)
select *,
lag(Current_Sales) over (partition by product_name order by Years) as Pv_Yrs_Sales, -- YEAR OVER YEAR ANALYSIS
Current_Sales - lag(Current_Sales) over (partition by product_name order by Years) as Sale_diff,
case 
when Current_Sales - lag(Current_Sales) over (partition by product_name order by Years) > 0 then 'Sales Increased'
when Current_Sales - lag(Current_Sales) over (partition by product_name order by Years) < 0 then 'Sales Decreased'
else 'No change'
End as Sale_Change,
avg(Current_Sales) over (partition by product_name) as Avg_Sales,
Current_Sales - avg(Current_Sales) over (partition by product_name) as Avg_Diff,
case 
when Current_Sales - avg(Current_Sales) over (partition by product_name) > 0 then 'Above Avg'
when Current_Sales - avg(Current_Sales) over (partition by product_name) < 0 then 'Below Avg'
else 'Avg'
End as Avg_Change
from yearly_product_sales
order by product_name, Years



-- PART TO WHOLE ANALYSIS

-- CATEGORIES WHICH CONTRIBUTE TO THE OVERALL SALES

with category_sales as (
                        select 
                        p.category,
                        sum(s.sales_amount) as Total_Sales
                        from gold.fact_sales s
                        left join gold.dim_products p 
                        on s.product_key = p.product_key
                        group by p.category
                        )
select *,
sum(Total_Sales) over () as Overall_Sales,
concat(round((cast(Total_Sales as float)/sum(Total_Sales) over ()) * 100 ,2), '%') as Percentage_Share
from category_sales
order by Total_Sales Desc

-- CATEGORIES WITCH CONTIBUTE TO OVERALL ORDERS
with category_orders as (
                        select 
                        p.category,
                        sum(s.quantity) as Total_Orders
                        from gold.fact_sales s
                        left join gold.dim_products p 
                        on s.product_key = p.product_key
                        group by p.category
                        )
select *,
sum(Total_Orders) over () as Overall_Orders,
concat(round((cast(Total_Orders as float)/sum(Total_Orders) over ()) * 100 ,2), '%') as Percentage_Share
from category_orders
order by Total_Orders Desc

-- SUBCATEGORIES WHICH CONTRIBUTE TO THE OVERALL SALES

with subcategory_sales as (
                        select 
                        p.subcategory,
                        sum(s.sales_amount) as Total_Sales
                        from gold.fact_sales s
                        left join gold.dim_products p 
                        on s.product_key = p.product_key
                        group by p.subcategory
                        )
select *,
sum(Total_Sales) over () as Overall_Sales,
concat(round((cast(Total_Sales as float)/sum(Total_Sales) over ()) * 100 ,2), '%') as Percentage_Share
from subcategory_sales
order by Total_Sales Desc

-- SUBCATEGORIES WITCH CONTIBUTE TO OVERALL ORDERS
with subcategory_orders as (
                        select 
                        p.subcategory,
                        sum(s.quantity) as Total_Orders
                        from gold.fact_sales s
                        left join gold.dim_products p 
                        on s.product_key = p.product_key
                        group by p.subcategory
                        )
select *,
sum(Total_Orders) over () as Overall_Orders,
concat(round((cast(Total_Orders as float)/sum(Total_Orders) over ()) * 100 ,2), '%') as Percentage_Share
from subcategory_orders
order by Total_Orders Desc

-- DATA SEGMENTATION

-- SEGMENTING PRODUCTS INTO COST RANGES AND CHECKING HOW MANY PRODUCTS FALL INTO EACH CATEGORY.
with product_segments as (
                        select product_key,
                        product_name,
                        cost,
                        case 
                        when cost < 100 then 'Below 100'
                        when cost between 100 and 500 then '100 - 500'
                        when cost between 500 and 1000 then '500 - 1000'
                        else 'Above 1000'
                        End as Cost_Range
                        from gold.dim_products )
select Cost_Range,
count(product_key) as No_of_Products
from product_segments
group by Cost_Range
order by No_of_Products desc


/*Group customers into three segments based on their spending behavior:
	- VIP: Customers with at least 12 months of history and spending more than €5,000.
	- Regular: Customers with at least 12 months of history but spending €5,000 or less.
	- New: Customers with a lifespan less than 12 months.
And find the total number of customers by each group */
with customer_spending as (
                            select c.customer_key,
                            sum(s.sales_amount) as Total_Sale,
                            min(s.order_date) as first_order,
                            max(s.order_date) as last_order,
                            datediff(month, min(s.order_date), max(s.order_date)) as order_history_Months
                            from gold.fact_sales s
                            left join gold.dim_customers c
                            on s.customer_key = c.customer_key
                            group by c.customer_key
                            ),
customer_segments as(
                            select customer_key,
                            Total_Sale,
                            order_history_Months,
                            case 
                            when Total_Sale > 5000 and order_history_Months >= 12  then 'VIP'
                            when Total_Sale <= 5000 and order_history_Months >= 12  then 'REGULAR'
                            else 'NEW'
                            end as customer_segments
                            from customer_spending
                            )
select customer_segments,
count(customer_key) as Total_Customers
from customer_segments
group by customer_segments
order by Total_Customers Desc
                            


/*
===============================================================================
Customer Report
===============================================================================
Purpose:
    - This report consolidates key customer metrics and behaviors

Highlights:
    1. Gathers essential fields such as names, ages, and transaction details.
	2. Segments customers into categories (VIP, Regular, New) and age groups.
    3. Aggregates customer-level metrics:
	   - total orders
	   - total sales
	   - total quantity purchased
	   - total products
	   - lifespan (in months)
    4. Calculates valuable KPIs:
	    - recency (months since last order)
		- average order value
		- average monthly spend
===============================================================================
*/

create view gold.report_customers as 

with base_query as (
-- 1) Base Query: Retrieves core columns from tables
                            select 
                            s.order_number,
                            s.product_key,
                            s.order_date,
                            s.sales_amount,
                            s.quantity,
                            c.customer_key,
                            c.customer_number,
                            concat(c.first_name, ' ' , c.last_name) as Cust_Name,
                            datediff(year, c.birthdate, getdate()) as Age
                            from gold.fact_sales s
                            left join gold.dim_customers c
                            on c.customer_key = s.customer_key
                            where order_date is not null
                            ),
customer_aggregation as (
-- 2) Customer Aggregations: Summarizes key metrics at the customer level
                            select customer_key,
                            customer_number,
                            Cust_Name,
                            Age,
                            count(distinct(order_number)) as Total_Orders,
                            SUM(sales_amount) AS total_sales,
                            SUM(quantity) AS total_quantity,
                            COUNT(DISTINCT product_key) AS total_products,
                            MAX(order_date) AS last_order_date,
                            DATEDIFF(month, MIN(order_date), MAX(order_date)) AS lifespan
                            from base_query
                            group by customer_key, customer_number, Cust_Name, Age
                            )
select 
customer_key,
customer_number,
Cust_Name,
Age,
case
when Age < 20 then 'BELOW 20'
when Age between 20 and 29 then '20-29'
when Age between 30 and 39 then '30-39'
when Age between 40 and 49 then '40-49'
else '50 AND ABOVE'
end as Age_Groups,
case
when Total_Sales > 5000 and lifespan >= 12  then 'VIP'
when Total_Sales <= 5000 and lifespan >= 12  then 'REGULAR'
else 'NEW'
end as customer_segments,
last_order_date,
datediff(month, last_order_date, getdate()) as Recency,
Total_Orders,
total_sales,
case 
when Total_Orders = 0 then 0
else total_sales /Total_Orders
end as Avg_Order_Value, -- AVO
total_quantity,
total_products,
lifespan,
case 
when lifespan = 0 then total_sales
else total_sales/lifespan 
end as Avg_Monthly_Spend
from customer_aggregation

select * from gold.report_customers



/*
===============================================================================
Product Report
===============================================================================
Purpose:
    - This report consolidates key product metrics and behaviors.

Highlights:
    1. Gathers essential fields such as product name, category, subcategory, and cost.
    2. Segments products by revenue to identify High-Performers, Mid-Range, or Low-Performers.
    3. Aggregates product-level metrics:
       - total orders
       - total sales
       - total quantity sold
       - total customers (unique)
       - lifespan (in months)
    4. Calculates valuable KPIs:
       - recency (months since last sale)
       - average order revenue (AOR)
       - average monthly revenue
===============================================================================
*/

CREATE VIEW gold.report_products AS

WITH base_query AS (
/*---------------------------------------------------------------------------
1) Base Query: Retrieves core columns from fact_sales and dim_products
---------------------------------------------------------------------------*/
    SELECT
	    f.order_number,
        f.order_date,
		f.customer_key,
        f.sales_amount,
        f.quantity,
        p.product_key,
        p.product_name,
        p.category,
        p.subcategory,
        p.cost
    FROM gold.fact_sales f
    LEFT JOIN gold.dim_products p
        ON f.product_key = p.product_key
    WHERE order_date IS NOT NULL  -- only consider valid sales dates
),

product_aggregations AS (
/*---------------------------------------------------------------------------
2) Product Aggregations: Summarizes key metrics at the product level
---------------------------------------------------------------------------*/
SELECT
    product_key,
    product_name,
    category,
    subcategory,
    cost,
    DATEDIFF(MONTH, MIN(order_date), MAX(order_date)) AS lifespan,
    MAX(order_date) AS last_sale_date,
    COUNT(DISTINCT order_number) AS total_orders,
	COUNT(DISTINCT customer_key) AS total_customers,
    SUM(sales_amount) AS total_sales,
    SUM(quantity) AS total_quantity,
	ROUND(AVG(CAST(sales_amount AS FLOAT) / NULLIF(quantity, 0)),1) AS avg_selling_price
FROM base_query

GROUP BY
    product_key,
    product_name,
    category,
    subcategory,
    cost
)

/*---------------------------------------------------------------------------
  3) Final Query: Combines all product results into one output
---------------------------------------------------------------------------*/
SELECT 
	product_key,
	product_name,
	category,
	subcategory,
	cost,
	last_sale_date,
	DATEDIFF(MONTH, last_sale_date, GETDATE()) AS recency_in_months,
	CASE
		WHEN total_sales > 50000 THEN 'High-Performer'
		WHEN total_sales >= 10000 THEN 'Mid-Range'
		ELSE 'Low-Performer'
	END AS product_segment,
	lifespan,
	total_orders,
	total_sales,
	total_quantity,
	total_customers,
	avg_selling_price,
	-- Average Order Revenue (AOR)
	CASE 
		WHEN total_orders = 0 THEN 0
		ELSE total_sales / total_orders
	END AS avg_order_revenue,

	-- Average Monthly Revenue
	CASE
		WHEN lifespan = 0 THEN total_sales
		ELSE total_sales / lifespan
	END AS avg_monthly_revenue

FROM product_aggregations 

select * from gold.report_products